name: test_sketch

on: [push, pull_request]

jobs:
  test-matrix:
    strategy:
      matrix:
        arduino-platform: ["esp8266:esp8266"]
        include:
          - arduino-platform: "esp8266:esp8266"
            fqbn: "esp8266:esp8266:nodemcu"

    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository content
        uses: actions/checkout@master
      - name: Set up the Arduino CLI
        uses: arduino/setup-arduino-cli@v1.1.1
      - name: Install platform
        run: |
          arduino-cli core update-index
          arduino-cli core install ${{ matrix.arduino-platform }} --additional-urls http://arduino.esp8266.com/stable/package_esp8266com_index.json
      - name: Install dependencies
        run: |
          arduino-cli lib install WiFiManager
          arduino-cli lib install RunningMedian
          arduino-cli lib install ArduinoJson@5.13.5
          arduino-cli lib install "Adafruit NeoPixel"
          arduino-cli lib install "SparkFun SCD30 Arduino Library"
      - name: Compile the sketch
        run: arduino-cli compile --fqbn ${{ matrix.fqbn }} ./ampel-main
